//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERGIA
    {
        public ALERGIA()
        {
            this.FICHA_MEDICA = new HashSet<FICHA_MEDICA>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<FICHA_MEDICA> FICHA_MEDICA { get; set; }
    }
}
