//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA
    {
        public short ID { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA { get; set; }
        public short CURSO_ID { get; set; }
        public short TRABAJADOR_ID { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
