//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION
    {
        public ATENCION()
        {
            this.EXAMEN = new HashSet<EXAMEN>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_ATENCION { get; set; }
        public short FICHA_MEDICA_ID { get; set; }
        public short VISITA_MEDICA_ID { get; set; }
    
        public virtual FICHA_MEDICA FICHA_MEDICA { get; set; }
        public virtual VISITA_MEDICA VISITA_MEDICA { get; set; }
        public virtual ICollection<EXAMEN> EXAMEN { get; set; }
    }
}
