//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesSafe : DbContext
    {
        public EntitiesSafe()
            : base("name=EntitiesSafe")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALERGIA> ALERGIA { get; set; }
        public DbSet<ASISTENCIA> ASISTENCIA { get; set; }
        public DbSet<ATENCION> ATENCION { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<EVALUACION> EVALUACION { get; set; }
        public DbSet<EXAMEN> EXAMEN { get; set; }
        public DbSet<FICHA_MEDICA> FICHA_MEDICA { get; set; }
        public DbSet<INFORME_FINAL> INFORME_FINAL { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
        public DbSet<PLAN_CAPACITACION> PLAN_CAPACITACION { get; set; }
        public DbSet<REGISTRO_PARTICIPANTES> REGISTRO_PARTICIPANTES { get; set; }
        public DbSet<TIPO_EVALUACION> TIPO_EVALUACION { get; set; }
        public DbSet<TIPO_EXAMEN> TIPO_EXAMEN { get; set; }
        public DbSet<TRABAJADOR> TRABAJADOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA_MEDICA> VISITA_MEDICA { get; set; }
        public DbSet<FERIADO> FERIADO { get; set; }
    
        public virtual int FN_VERCONTRATO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VERCONTRATO");
        }
    
        public virtual int FN_VEREXAMEN(Nullable<decimal> iD_ATENCION)
        {
            var iD_ATENCIONParameter = iD_ATENCION.HasValue ?
                new ObjectParameter("ID_ATENCION", iD_ATENCION) :
                new ObjectParameter("ID_ATENCION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VEREXAMEN", iD_ATENCIONParameter);
        }
    
        public virtual int FN_VERTIPODEEVALUACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VERTIPODEEVALUACION");
        }
    
        public virtual int FN_VERUSUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VERUSUARIOS");
        }
    
        public virtual int FN_VERVISITASMEDICAS(Nullable<decimal> iD_MEDICO)
        {
            var iD_MEDICOParameter = iD_MEDICO.HasValue ?
                new ObjectParameter("ID_MEDICO", iD_MEDICO) :
                new ObjectParameter("ID_MEDICO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VERVISITASMEDICAS", iD_MEDICOParameter);
        }
    
        public virtual int FN_VERVISITASMEDICASPORFECHA(Nullable<System.DateTime> fECHA_VISITA)
        {
            var fECHA_VISITAParameter = fECHA_VISITA.HasValue ?
                new ObjectParameter("FECHA_VISITA", fECHA_VISITA) :
                new ObjectParameter("FECHA_VISITA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_VERVISITASMEDICASPORFECHA", fECHA_VISITAParameter);
        }
    
        public virtual int PR_CERRARCONTRATO(Nullable<decimal> iD_CONTRATO)
        {
            var iD_CONTRATOParameter = iD_CONTRATO.HasValue ?
                new ObjectParameter("ID_CONTRATO", iD_CONTRATO) :
                new ObjectParameter("ID_CONTRATO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CERRARCONTRATO", iD_CONTRATOParameter);
        }
    
        public virtual int PR_CERRARPLAN(Nullable<decimal> iD_PLAN)
        {
            var iD_PLANParameter = iD_PLAN.HasValue ?
                new ObjectParameter("ID_PLAN", iD_PLAN) :
                new ObjectParameter("ID_PLAN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CERRARPLAN", iD_PLANParameter);
        }
    
        public virtual int PR_CREARATENCION(string dESC_ATENCION, Nullable<decimal> iD_FICHA, Nullable<decimal> iD_VISITA_MEDICA)
        {
            var dESC_ATENCIONParameter = dESC_ATENCION != null ?
                new ObjectParameter("DESC_ATENCION", dESC_ATENCION) :
                new ObjectParameter("DESC_ATENCION", typeof(string));
    
            var iD_FICHAParameter = iD_FICHA.HasValue ?
                new ObjectParameter("ID_FICHA", iD_FICHA) :
                new ObjectParameter("ID_FICHA", typeof(decimal));
    
            var iD_VISITA_MEDICAParameter = iD_VISITA_MEDICA.HasValue ?
                new ObjectParameter("ID_VISITA_MEDICA", iD_VISITA_MEDICA) :
                new ObjectParameter("ID_VISITA_MEDICA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARATENCION", dESC_ATENCIONParameter, iD_FICHAParameter, iD_VISITA_MEDICAParameter);
        }
    
        public virtual int PR_CREARCAPACITACION(string dESC_CAPACITACION, Nullable<decimal> mIN_PARTICIPANTES, string nOM_EXPOSITOR, Nullable<System.DateTime> fECHA_FINAL, Nullable<decimal> iD_PLAN_CAPACITACION)
        {
            var dESC_CAPACITACIONParameter = dESC_CAPACITACION != null ?
                new ObjectParameter("DESC_CAPACITACION", dESC_CAPACITACION) :
                new ObjectParameter("DESC_CAPACITACION", typeof(string));
    
            var mIN_PARTICIPANTESParameter = mIN_PARTICIPANTES.HasValue ?
                new ObjectParameter("MIN_PARTICIPANTES", mIN_PARTICIPANTES) :
                new ObjectParameter("MIN_PARTICIPANTES", typeof(decimal));
    
            var nOM_EXPOSITORParameter = nOM_EXPOSITOR != null ?
                new ObjectParameter("NOM_EXPOSITOR", nOM_EXPOSITOR) :
                new ObjectParameter("NOM_EXPOSITOR", typeof(string));
    
            var fECHA_FINALParameter = fECHA_FINAL.HasValue ?
                new ObjectParameter("FECHA_FINAL", fECHA_FINAL) :
                new ObjectParameter("FECHA_FINAL", typeof(System.DateTime));
    
            var iD_PLAN_CAPACITACIONParameter = iD_PLAN_CAPACITACION.HasValue ?
                new ObjectParameter("ID_PLAN_CAPACITACION", iD_PLAN_CAPACITACION) :
                new ObjectParameter("ID_PLAN_CAPACITACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARCAPACITACION", dESC_CAPACITACIONParameter, mIN_PARTICIPANTESParameter, nOM_EXPOSITORParameter, fECHA_FINALParameter, iD_PLAN_CAPACITACIONParameter);
        }
    
        public virtual int PR_CREARCONTRATO(string dESC_CONTRATO, Nullable<System.DateTime> fECHA_INICIO_CONTRATO, Nullable<decimal> iD_EMPRESA)
        {
            var dESC_CONTRATOParameter = dESC_CONTRATO != null ?
                new ObjectParameter("DESC_CONTRATO", dESC_CONTRATO) :
                new ObjectParameter("DESC_CONTRATO", typeof(string));
    
            var fECHA_INICIO_CONTRATOParameter = fECHA_INICIO_CONTRATO.HasValue ?
                new ObjectParameter("FECHA_INICIO_CONTRATO", fECHA_INICIO_CONTRATO) :
                new ObjectParameter("FECHA_INICIO_CONTRATO", typeof(System.DateTime));
    
            var iD_EMPRESAParameter = iD_EMPRESA.HasValue ?
                new ObjectParameter("ID_EMPRESA", iD_EMPRESA) :
                new ObjectParameter("ID_EMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARCONTRATO", dESC_CONTRATOParameter, fECHA_INICIO_CONTRATOParameter, iD_EMPRESAParameter);
        }
    
        public virtual int PR_CREARCURSO(string dESC_CURSO, Nullable<decimal> cAPAC_ID)
        {
            var dESC_CURSOParameter = dESC_CURSO != null ?
                new ObjectParameter("DESC_CURSO", dESC_CURSO) :
                new ObjectParameter("DESC_CURSO", typeof(string));
    
            var cAPAC_IDParameter = cAPAC_ID.HasValue ?
                new ObjectParameter("CAPAC_ID", cAPAC_ID) :
                new ObjectParameter("CAPAC_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARCURSO", dESC_CURSOParameter, cAPAC_IDParameter);
        }
    
        public virtual int PR_CREAREXAMEN(string dESC_EXAMEN, Nullable<System.DateTime> f_EXAMEN, Nullable<decimal> iD_TIPO_EXAMEN, Nullable<decimal> iD_ATENCION)
        {
            var dESC_EXAMENParameter = dESC_EXAMEN != null ?
                new ObjectParameter("DESC_EXAMEN", dESC_EXAMEN) :
                new ObjectParameter("DESC_EXAMEN", typeof(string));
    
            var f_EXAMENParameter = f_EXAMEN.HasValue ?
                new ObjectParameter("F_EXAMEN", f_EXAMEN) :
                new ObjectParameter("F_EXAMEN", typeof(System.DateTime));
    
            var iD_TIPO_EXAMENParameter = iD_TIPO_EXAMEN.HasValue ?
                new ObjectParameter("ID_TIPO_EXAMEN", iD_TIPO_EXAMEN) :
                new ObjectParameter("ID_TIPO_EXAMEN", typeof(decimal));
    
            var iD_ATENCIONParameter = iD_ATENCION.HasValue ?
                new ObjectParameter("ID_ATENCION", iD_ATENCION) :
                new ObjectParameter("ID_ATENCION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREAREXAMEN", dESC_EXAMENParameter, f_EXAMENParameter, iD_TIPO_EXAMENParameter, iD_ATENCIONParameter);
        }
    
        public virtual int PR_CREARPLAN(string dESC_PLAN, Nullable<decimal> iD_CONTRATO)
        {
            var dESC_PLANParameter = dESC_PLAN != null ?
                new ObjectParameter("DESC_PLAN", dESC_PLAN) :
                new ObjectParameter("DESC_PLAN", typeof(string));
    
            var iD_CONTRATOParameter = iD_CONTRATO.HasValue ?
                new ObjectParameter("ID_CONTRATO", iD_CONTRATO) :
                new ObjectParameter("ID_CONTRATO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARPLAN", dESC_PLANParameter, iD_CONTRATOParameter);
        }
    
        public virtual int PR_CREARTIPODEEVALUACION(string dESCRIPCION)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARTIPODEEVALUACION", dESCRIPCIONParameter);
        }
    
        public virtual int PR_CREARUSUARIO(Nullable<decimal> rUT, string cONTRASEÑA, string nOMBRE, string aPE_PATERNO, string aPE_MATERNO, string dIRECCION, Nullable<decimal> tELEFONO, string eMAIL, Nullable<System.DateTime> fECHA_REGISTRO, Nullable<decimal> iD_PERFIL_USUARIO)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPE_PATERNOParameter = aPE_PATERNO != null ?
                new ObjectParameter("APE_PATERNO", aPE_PATERNO) :
                new ObjectParameter("APE_PATERNO", typeof(string));
    
            var aPE_MATERNOParameter = aPE_MATERNO != null ?
                new ObjectParameter("APE_MATERNO", aPE_MATERNO) :
                new ObjectParameter("APE_MATERNO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fECHA_REGISTROParameter = fECHA_REGISTRO.HasValue ?
                new ObjectParameter("FECHA_REGISTRO", fECHA_REGISTRO) :
                new ObjectParameter("FECHA_REGISTRO", typeof(System.DateTime));
    
            var iD_PERFIL_USUARIOParameter = iD_PERFIL_USUARIO.HasValue ?
                new ObjectParameter("ID_PERFIL_USUARIO", iD_PERFIL_USUARIO) :
                new ObjectParameter("ID_PERFIL_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARUSUARIO", rUTParameter, cONTRASEÑAParameter, nOMBREParameter, aPE_PATERNOParameter, aPE_MATERNOParameter, dIRECCIONParameter, tELEFONOParameter, eMAILParameter, fECHA_REGISTROParameter, iD_PERFIL_USUARIOParameter);
        }
    
        public virtual int PR_CREARVISITA(Nullable<System.DateTime> fEC_VISITA, Nullable<decimal> iD_CONTRATO, Nullable<decimal> iD_MEDICO)
        {
            var fEC_VISITAParameter = fEC_VISITA.HasValue ?
                new ObjectParameter("FEC_VISITA", fEC_VISITA) :
                new ObjectParameter("FEC_VISITA", typeof(System.DateTime));
    
            var iD_CONTRATOParameter = iD_CONTRATO.HasValue ?
                new ObjectParameter("ID_CONTRATO", iD_CONTRATO) :
                new ObjectParameter("ID_CONTRATO", typeof(decimal));
    
            var iD_MEDICOParameter = iD_MEDICO.HasValue ?
                new ObjectParameter("ID_MEDICO", iD_MEDICO) :
                new ObjectParameter("ID_MEDICO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CREARVISITA", fEC_VISITAParameter, iD_CONTRATOParameter, iD_MEDICOParameter);
        }
    
        public virtual int PR_ELIMINARCAPACITACION(Nullable<decimal> iD_CAPACITACION)
        {
            var iD_CAPACITACIONParameter = iD_CAPACITACION.HasValue ?
                new ObjectParameter("ID_CAPACITACION", iD_CAPACITACION) :
                new ObjectParameter("ID_CAPACITACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ELIMINARCAPACITACION", iD_CAPACITACIONParameter);
        }
    
        public virtual int PR_ELIMINAREVALUACION(Nullable<decimal> iD_EVALUACION)
        {
            var iD_EVALUACIONParameter = iD_EVALUACION.HasValue ?
                new ObjectParameter("ID_EVALUACION", iD_EVALUACION) :
                new ObjectParameter("ID_EVALUACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ELIMINAREVALUACION", iD_EVALUACIONParameter);
        }
    
        public virtual int PR_MODIFICARTIPOEVALUACION(Nullable<decimal> iD_EVALUACION, string dESCRIPCION_MOD)
        {
            var iD_EVALUACIONParameter = iD_EVALUACION.HasValue ?
                new ObjectParameter("ID_EVALUACION", iD_EVALUACION) :
                new ObjectParameter("ID_EVALUACION", typeof(decimal));
    
            var dESCRIPCION_MODParameter = dESCRIPCION_MOD != null ?
                new ObjectParameter("DESCRIPCION_MOD", dESCRIPCION_MOD) :
                new ObjectParameter("DESCRIPCION_MOD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_MODIFICARTIPOEVALUACION", iD_EVALUACIONParameter, dESCRIPCION_MODParameter);
        }
    
        public virtual int PR_MODIFICARUSUARIO(Nullable<decimal> rUT, string cONTRASEÑA, string nOMBRE, string aPE_PATERNO, string aPE_MATERNO, string dIRECCION, Nullable<decimal> tELEFONO, string eMAIL, Nullable<System.DateTime> fECHA_REGISTRO, Nullable<decimal> iD_PERFIL_USUARIO)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPE_PATERNOParameter = aPE_PATERNO != null ?
                new ObjectParameter("APE_PATERNO", aPE_PATERNO) :
                new ObjectParameter("APE_PATERNO", typeof(string));
    
            var aPE_MATERNOParameter = aPE_MATERNO != null ?
                new ObjectParameter("APE_MATERNO", aPE_MATERNO) :
                new ObjectParameter("APE_MATERNO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var fECHA_REGISTROParameter = fECHA_REGISTRO.HasValue ?
                new ObjectParameter("FECHA_REGISTRO", fECHA_REGISTRO) :
                new ObjectParameter("FECHA_REGISTRO", typeof(System.DateTime));
    
            var iD_PERFIL_USUARIOParameter = iD_PERFIL_USUARIO.HasValue ?
                new ObjectParameter("ID_PERFIL_USUARIO", iD_PERFIL_USUARIO) :
                new ObjectParameter("ID_PERFIL_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_MODIFICARUSUARIO", rUTParameter, cONTRASEÑAParameter, nOMBREParameter, aPE_PATERNOParameter, aPE_MATERNOParameter, dIRECCIONParameter, tELEFONOParameter, eMAILParameter, fECHA_REGISTROParameter, iD_PERFIL_USUARIOParameter);
        }
    }
}
