//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDSafeEntities : DbContext
    {
        public BDSafeEntities()
            : base("name=BDSafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALERGIA> ALERGIA { get; set; }
        public DbSet<ASISTENCIA> ASISTENCIA { get; set; }
        public DbSet<ATENCION> ATENCION { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<EVALUACION> EVALUACION { get; set; }
        public DbSet<EXAMEN> EXAMEN { get; set; }
        public DbSet<FICHA_MEDICA> FICHA_MEDICA { get; set; }
        public DbSet<INFORME_FINAL> INFORME_FINAL { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
        public DbSet<PLAN_CAPACITACION> PLAN_CAPACITACION { get; set; }
        public DbSet<TIPO_EVALUACION> TIPO_EVALUACION { get; set; }
        public DbSet<TIPO_EXAMEN> TIPO_EXAMEN { get; set; }
        public DbSet<TRABAJADOR> TRABAJADOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA_MEDICA> VISITA_MEDICA { get; set; }
        public DbSet<FERIADO> FERIADO { get; set; }
    }
}
