//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public CAPACITACION()
        {
            this.CURSO = new HashSet<CURSO>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION { get; set; }
        public short PARTICIPANTES_MIN { get; set; }
        public string EXPOSITOR { get; set; }
        public System.DateTime FECHA_COMIENZO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public short PLAN_CAPACITACION_ID { get; set; }
    
        public virtual PLAN_CAPACITACION PLAN_CAPACITACION { get; set; }
        public virtual ICollection<CURSO> CURSO { get; set; }
    }
}
