//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.EVALUACION = new HashSet<EVALUACION>();
            this.PLAN_CAPACITACION = new HashSet<PLAN_CAPACITACION>();
            this.TRABAJADOR = new HashSet<TRABAJADOR>();
            this.VISITA_MEDICA = new HashSet<VISITA_MEDICA>();
        }
    
        public short ID { get; set; }
        public string CONTRATO1 { get; set; }
        public System.DateTime FECHA_INICIO_CONTRATO { get; set; }
        public short USUARIO_ID { get; set; }
        public string ESTADO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
        public virtual ICollection<PLAN_CAPACITACION> PLAN_CAPACITACION { get; set; }
        public virtual ICollection<TRABAJADOR> TRABAJADOR { get; set; }
        public virtual ICollection<VISITA_MEDICA> VISITA_MEDICA { get; set; }
    }
}
