//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.ASISTENCIA = new HashSet<ASISTENCIA>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION { get; set; }
        public short CAPACITACION_ID { get; set; }
        public short TRABAJADOR_ID { get; set; }
    
        public virtual ICollection<ASISTENCIA> ASISTENCIA { get; set; }
        public virtual CAPACITACION CAPACITACION { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
    }
}
