//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACION
    {
        public EVALUACION()
        {
            this.INFORME_FINAL = new HashSet<INFORME_FINAL>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public short ID { get; set; }
        public System.DateTime FECHA_EVALUACION { get; set; }
        public string DESCRIPCION_EVALUACION { get; set; }
        public short TIPO_EVALUACION_ID { get; set; }
        public short CONTRATO_ID { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual TIPO_EVALUACION TIPO_EVALUACION { get; set; }
        public virtual ICollection<INFORME_FINAL> INFORME_FINAL { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
