//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA_MEDICA
    {
        public FICHA_MEDICA()
        {
            this.ATENCION = new HashSet<ATENCION>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_FICHA { get; set; }
        public short TRABAJADOR_ID { get; set; }
        public string ESTATURA { get; set; }
        public string PESO { get; set; }
        public short ALERGIA_ID { get; set; }
        public string GRUPO_SANGUINEO { get; set; }
    
        public virtual ALERGIA ALERGIA { get; set; }
        public virtual ICollection<ATENCION> ATENCION { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
    }
}
