//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_FINAL
    {
        public short ID { get; set; }
        public string RECOMENDACION { get; set; }
        public short USUARIO_ID { get; set; }
        public string ESTADO { get; set; }
        public short EVALUACION_ID { get; set; }
    
        public virtual EVALUACION EVALUACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
