//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.VISITA_MEDICA = new HashSet<VISITA_MEDICA>();
        }
    
        public short ID { get; set; }
        public string DISPONIBILIDAD { get; set; }
        public string EMAIL_PRIVADO { get; set; }
        public Nullable<decimal> TELEFONO_PRIVADO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<VISITA_MEDICA> VISITA_MEDICA { get; set; }
    }
}
