//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_CAPACITACION
    {
        public PLAN_CAPACITACION()
        {
            this.CAPACITACION = new HashSet<CAPACITACION>();
        }
    
        public short ID { get; set; }
        public string DESCRIPCION_PLAN { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public short CONTRATO_ID { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
