//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EXAMEN
    {
        public TIPO_EXAMEN()
        {
            this.EXAMEN = new HashSet<EXAMEN>();
        }
    
        public short ID { get; set; }
        public string TIPO_EXAMEN1 { get; set; }
    
        public virtual ICollection<EXAMEN> EXAMEN { get; set; }
    }
}
