//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADOR
    {
        public TRABAJADOR()
        {
            this.CURSO = new HashSet<CURSO>();
            this.FICHA_MEDICA = new HashSet<FICHA_MEDICA>();
        }
    
        public short ID { get; set; }
        public short CONTRATO_ID { get; set; }
        public string EMAIL_PRIVADO { get; set; }
        public Nullable<decimal> TELEFONO_PRIVADO { get; set; }
        public string ESTADO_RIESGO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<CURSO> CURSO { get; set; }
        public virtual ICollection<FICHA_MEDICA> FICHA_MEDICA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
