//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.INFORME_FINAL = new HashSet<INFORME_FINAL>();
            this.EVALUACION = new HashSet<EVALUACION>();
        }
    
        public short ID { get; set; }
        public long RUT_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string NOMBRE { get; set; }
        public string APE_PATERNO { get; set; }
        public string APE_MATERNO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime REGISTRO { get; set; }
        public short PERFIL_USUARIO_ID { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<INFORME_FINAL> INFORME_FINAL { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PERFIL_USUARIO PERFIL_USUARIO { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
    }
}
