//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSafe.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_MEDICA
    {
        public VISITA_MEDICA()
        {
            this.ATENCION = new HashSet<ATENCION>();
        }
    
        public short ID { get; set; }
        public System.DateTime FECHA_VISITA { get; set; }
        public string ESTADO { get; set; }
        public short CONTRATO_ID { get; set; }
        public short MEDICO_USUARIO_ID { get; set; }
    
        public virtual ICollection<ATENCION> ATENCION { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual MEDICO MEDICO { get; set; }
    }
}
